platform :ios, '13.0'

target 'Kiwi' do
  use_frameworks!

  # Pods for Kiwi
  pod 'Firebase/Auth'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.9.0'
end
